#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1

BINARY="/solarmatrix/solarmatrix-watchdog"

start_service() {
    [ -x "$BINARY" ] || return 1

    procd_open_instance
    procd_set_param command "$BINARY"
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
